"""Render a HealthReport as a vault ``run`` record.

Mirrors ``alfred.brief.renderer`` so the output fits the existing
``run`` type convention — frontmatter dict + body string, serialized
together via ``serialize_record``.  The body embeds the human-readable
rendering from ``alfred.health.renderer`` plus a JSON appendix so
operators can `jq` over the record.
"""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

from alfred.health.renderer import render_human, render_json
from alfred.health.types import HealthReport, Status

from .config import BITConfig


def _tool_counts(report: HealthReport) -> dict[str, int]:
    """Aggregate tool-level status counts."""
    counts = {"ok": 0, "warn": 0, "fail": 0, "skip": 0}
    for tool in report.tools:
        key = tool.status.value if isinstance(tool.status, Status) else str(tool.status)
        counts[key] = counts.get(key, 0) + 1
    return counts


def render_bit_record(
    report: HealthReport,
    date_str: str,
    config: BITConfig,
) -> tuple[dict, str]:
    """Render a BIT report as a ``(frontmatter_dict, body)`` tuple.

    Args:
        report: The completed HealthReport.
        date_str: ``YYYY-MM-DD`` — goes into the filename and
            frontmatter.
        config: BITConfig, for timezone + name_template.

    Returns:
        ``(frontmatter_dict, body_str)`` — suitable for
        ``alfred.brief.renderer.serialize_record`` (shared helper).
    """
    tz = ZoneInfo(config.schedule.timezone)
    now = datetime.now(tz)
    time_str = now.strftime("%H%M %Z")

    name = config.output.name_template.replace("{date}", date_str)
    counts = _tool_counts(report)
    tool_list = [t.tool for t in report.tools]

    frontmatter = {
        "type": "run",
        "status": "completed",
        "name": name,
        "description": "Alfred built-in test (health sweep)",
        "process": "[[process/Alfred BIT]]",
        "trigger": "scheduled",
        "started": now.isoformat(),
        "created": date_str,
        "overall_status": report.overall_status.value,
        "mode": report.mode,
        "tools_checked": tool_list,
        "tool_counts": counts,
        "tags": ["bit", "health", f"bit/{report.overall_status.value}"],
    }

    body_parts = [
        f"# {name}",
        "",
        f"Generated at {time_str}.",
        "",
        "## Summary",
        "",
    ]
    body_parts.extend(list(render_human(report)))
    body_parts.extend([
        "",
        "## Raw report (JSON)",
        "",
        "```json",
        render_json(report),
        "```",
        "",
        "---",
        "*Generated by Alfred BIT daemon*",
    ])

    body = "\n".join(body_parts)
    return frontmatter, body
