"""Tests for the brief's STAY-C Bug Relay section (task #21, downstream of #4).

The load-bearing property (pinned first): the brief reads ONLY the count from
the watcher's relay spool — bug bodies / summaries / ids NEVER cross into the
brief, even when the spool is in FULL mode. The brief transits Telegram and
STAY-C uses none, so only the PHI-free count may cross.

Also covers the intentionally-left-blank states — disabled (section omitted),
absent / unreadable / stale (explicit "no data" / "stale" line so a dead
watcher is VISIBLE) — the staleness boundary, and the config loader.

Fixtures are generated by the REAL producer (``stayc_bug_watcher.build_snapshot``)
wherever possible, so the parser is pinned against the actual cross-component
contract, not a paraphrase of it.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

import structlog

from alfred.brief.config import StaycBugRelayConfig, load_from_unified
from alfred.brief.stayc_relay import render_stayc_bug_relay_section
from alfred.scripts.stayc_bug_watcher import (
    FORWARD_MODE_FULL,
    FORWARD_MODE_LOCKED,
    build_snapshot,
    list_unresolved_reports,
)

_GEN_AT = "2026-07-18T03:20:10Z"
_NOW = datetime(2026, 7, 18, 4, 0, 0, tzinfo=timezone.utc)  # 40 min after gen


def _cfg(spool_path: str, *, enabled: bool = True, staleness_hours: float = 25.0):
    return StaycBugRelayConfig(
        enabled=enabled, spool_path=spool_path, staleness_hours=staleness_hours,
    )


def _write_report(bug_dir: Path, stem: str, *, summary: str, body: str) -> None:
    """A STAY-C bug report file as the clinical daemon would write it."""
    bug_dir.mkdir(parents=True, exist_ok=True)
    (bug_dir / f"{stem}.md").write_text(
        f"---\nsummary: {summary}\n---\n\n{body}\n", encoding="utf-8",
    )


def _locked_spool(tmp_path: Path, *, count: int, generated_at: str = _GEN_AT) -> Path:
    """A locked-mode spool with ``count`` opaque ids, via the real producer."""
    bug_dir = tmp_path / "bugs"
    for i in range(count):
        _write_report(bug_dir, f"ts{i:03d}-{i:04x}", summary=f"s{i}", body="b")
    reports = list_unresolved_reports(bug_dir)
    text = build_snapshot(
        FORWARD_MODE_LOCKED, reports, generated_at=generated_at, new_count=0,
    )
    spool = tmp_path / "relay.md"
    spool.write_text(text, encoding="utf-8")
    return spool


# --- The load-bearing pin: NO body content ever crosses --------------------


def test_full_mode_spool_renders_count_only_never_bodies(tmp_path) -> None:
    """A FULL-mode spool carries summaries + full bodies. The brief must
    render the COUNT and NONE of that body text. Mutation: make the parser
    read past the header into the body → the PHI sentinels leak and this
    fails. This is THE contract test."""
    bug_dir = tmp_path / "bugs"
    # PHI-shaped sentinels that must NEVER appear in the brief.
    _write_report(
        bug_dir, "ts001-aaaa",
        summary="PATIENT_SUMMARY_SENTINEL",
        body="BODY_PHI_SENTINEL diagnosis details here",
    )
    _write_report(
        bug_dir, "ts002-bbbb",
        summary="SECOND_SUMMARY_SENTINEL",
        body="SECOND_BODY_SENTINEL more detail",
    )
    reports = list_unresolved_reports(bug_dir)
    text = build_snapshot(
        FORWARD_MODE_FULL, reports, generated_at=_GEN_AT, new_count=2,
    )
    spool = tmp_path / "relay.md"
    spool.write_text(text, encoding="utf-8")
    # Sanity: the spool file itself DOES contain the bodies (full mode).
    assert "BODY_PHI_SENTINEL" in text

    out = render_stayc_bug_relay_section(_cfg(str(spool)), _NOW)

    assert out == "STAY-C: 2 unresolved bug reports."
    for sentinel in (
        "PATIENT_SUMMARY_SENTINEL", "BODY_PHI_SENTINEL",
        "SECOND_SUMMARY_SENTINEL", "SECOND_BODY_SENTINEL",
        "ts001-aaaa", "ts002-bbbb",   # opaque ids must not cross either
    ):
        assert sentinel not in out


# --- Fresh count rendering (locked mode, real producer) --------------------


def test_fresh_count_plural(tmp_path) -> None:
    spool = _locked_spool(tmp_path, count=3)
    assert render_stayc_bug_relay_section(_cfg(str(spool)), _NOW) == (
        "STAY-C: 3 unresolved bug reports."
    )


def test_fresh_count_singular(tmp_path) -> None:
    spool = _locked_spool(tmp_path, count=1)
    assert render_stayc_bug_relay_section(_cfg(str(spool)), _NOW) == (
        "STAY-C: 1 unresolved bug report."
    )


def test_fresh_count_zero(tmp_path) -> None:
    """Zero unresolved is an explicit line, not a blank (ILB)."""
    spool = _locked_spool(tmp_path, count=0)
    assert render_stayc_bug_relay_section(_cfg(str(spool)), _NOW) == (
        "STAY-C: no unresolved bug reports."
    )


# --- Disabled / config states ----------------------------------------------


def test_disabled_returns_empty(tmp_path) -> None:
    """Disabled → section omitted entirely (the one permitted silence)."""
    spool = _locked_spool(tmp_path, count=5)
    assert render_stayc_bug_relay_section(
        _cfg(str(spool), enabled=False), _NOW,
    ) == ""


def test_enabled_but_no_path_renders_not_configured(tmp_path) -> None:
    out = render_stayc_bug_relay_section(_cfg("", enabled=True), _NOW)
    assert "not configured" in out.lower()


# --- Intentionally-left-blank: absent / unreadable -------------------------


def test_absent_spool_renders_no_data(tmp_path) -> None:
    missing = tmp_path / "does_not_exist.md"
    out = render_stayc_bug_relay_section(_cfg(str(missing)), _NOW)
    assert "no data" in out.lower()
    assert "not found" in out.lower()


def test_unparseable_header_renders_no_data(tmp_path) -> None:
    """Present but no ``unresolved:`` header → no data (never trust a body we
    can't verify a fresh header on)."""
    spool = tmp_path / "relay.md"
    spool.write_text("garbage content\nno header here\n", encoding="utf-8")
    out = render_stayc_bug_relay_section(_cfg(str(spool)), _NOW)
    assert "no data" in out.lower()


# --- Staleness (dead watcher must be visible) ------------------------------


def test_stale_spool_renders_stale_not_count(tmp_path) -> None:
    """generated_at older than staleness_hours → the stale line, NOT a bare
    count (a stale count looks live — worse than no count)."""
    spool = _locked_spool(tmp_path, count=4, generated_at=_GEN_AT)
    # now = 26h after generated_at (> 25h threshold).
    now = datetime.strptime(_GEN_AT, "%Y-%m-%dT%H:%M:%SZ").replace(
        tzinfo=timezone.utc,
    ) + timedelta(hours=26)
    out = render_stayc_bug_relay_section(_cfg(str(spool)), now)
    assert "stale" in out.lower()
    assert "STAY-C: 4 unresolved" not in out


def test_staleness_boundary(tmp_path) -> None:
    """Just under the threshold renders the count; just over renders stale.
    Mutation: flip the comparison / off-by-one on the threshold → one of
    these fails."""
    gen = datetime.strptime(_GEN_AT, "%Y-%m-%dT%H:%M:%SZ").replace(
        tzinfo=timezone.utc,
    )
    spool = _locked_spool(tmp_path, count=2, generated_at=_GEN_AT)
    # 24h59m old → fresh.
    fresh = render_stayc_bug_relay_section(
        _cfg(str(spool)), gen + timedelta(hours=24, minutes=59),
    )
    assert fresh == "STAY-C: 2 unresolved bug reports."
    # 25h01m old → stale.
    stale = render_stayc_bug_relay_section(
        _cfg(str(spool)), gen + timedelta(hours=25, minutes=1),
    )
    assert "stale" in stale.lower()


# --- Log-emission pins (per feedback_log_emission_test_pattern) ------------


def test_log_emission_fresh(tmp_path) -> None:
    spool = _locked_spool(tmp_path, count=3)
    with structlog.testing.capture_logs() as cap:
        render_stayc_bug_relay_section(_cfg(str(spool)), _NOW)
    events = [c for c in cap if c.get("event") == "brief.stayc_relay"]
    assert len(events) == 1
    assert events[0]["state"] == "fresh"
    assert events[0]["count"] == 3


def test_log_emission_stale(tmp_path) -> None:
    spool = _locked_spool(tmp_path, count=1, generated_at=_GEN_AT)
    now = datetime.strptime(_GEN_AT, "%Y-%m-%dT%H:%M:%SZ").replace(
        tzinfo=timezone.utc,
    ) + timedelta(hours=30)
    with structlog.testing.capture_logs() as cap:
        render_stayc_bug_relay_section(_cfg(str(spool)), now)
    events = [c for c in cap if c.get("event") == "brief.stayc_relay"]
    assert len(events) == 1
    assert events[0]["state"] == "stale"
    assert events[0]["count"] == 1


def test_log_emission_absent(tmp_path) -> None:
    with structlog.testing.capture_logs() as cap:
        render_stayc_bug_relay_section(
            _cfg(str(tmp_path / "nope.md")), _NOW,
        )
    events = [c for c in cap if c.get("event") == "brief.stayc_relay"]
    assert len(events) == 1
    assert events[0]["state"] == "absent"


# --- Config loader ----------------------------------------------------------


def test_config_loads_stayc_bug_relay_block() -> None:
    cfg = load_from_unified({
        "vault": {"path": "/tmp/v"},
        "brief": {
            "stayc_bug_relay": {
                "enabled": True,
                "spool_path": "/data/algernon/alfred/data/stayc_bugs_relay.md",
                "staleness_hours": 12,
            },
        },
    })
    assert cfg.stayc_bug_relay.enabled is True
    assert cfg.stayc_bug_relay.spool_path == (
        "/data/algernon/alfred/data/stayc_bugs_relay.md"
    )
    assert cfg.stayc_bug_relay.staleness_hours == 12.0


def test_config_absent_block_defaults_disabled() -> None:
    """No block → disabled, no path (Salem-only opt-in; other instances get
    nothing). Mutation: default enabled=True → this fails."""
    cfg = load_from_unified({"vault": {"path": "/tmp/v"}, "brief": {}})
    assert cfg.stayc_bug_relay.enabled is False
    assert cfg.stayc_bug_relay.spool_path == ""
    assert cfg.stayc_bug_relay.staleness_hours == 25.0


def test_config_malformed_staleness_falls_back() -> None:
    cfg = load_from_unified({
        "vault": {"path": "/tmp/v"},
        "brief": {"stayc_bug_relay": {"enabled": True, "staleness_hours": "oops"}},
    })
    assert cfg.stayc_bug_relay.staleness_hours == 25.0
