"""Brief renderer — assembles sections into a vault record."""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

from .config import BriefConfig


def render_brief(
    date_str: str,
    sections: list[tuple[str, str]],
    config: BriefConfig,
) -> tuple[dict, str]:
    """Render a complete brief as (frontmatter_dict, body_string).

    Args:
        date_str: YYYY-MM-DD date for the brief.
        sections: List of (section_name, markdown_content) tuples.
        config: Brief configuration.

    Returns:
        Tuple of (frontmatter dict, body markdown string).
    """
    tz = ZoneInfo(config.schedule.timezone)
    now = datetime.now(tz)
    time_str = now.strftime("%H%M %Z")

    name = config.output.name_template.replace("{date}", date_str)

    frontmatter = {
        "type": "run",
        "status": "completed",
        "name": name,
        "description": "Daily operational briefing",
        "process": "[[process/Morning Brief]]",
        "trigger": "scheduled",
        "started": now.isoformat(),
        "created": date_str,
        "tags": ["brief", "daily"] + [s[0].lower() for s in sections],
    }

    body_parts = [
        f"# {name}",
        "",
        f"Generated at {time_str}.",
        "",
    ]

    for section_name, content in sections:
        body_parts.append(f"## {section_name}")
        body_parts.append("")
        body_parts.append(content)
        body_parts.append("")

    body_parts.append("---")
    body_parts.append("*Generated by Alfred Brief*")

    body = "\n".join(body_parts)
    return frontmatter, body


def serialize_record(frontmatter: dict, body: str) -> str:
    """Serialize frontmatter + body into a complete markdown file."""
    import yaml
    fm_str = yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return f"---\n{fm_str}---\n\n{body}\n"
